# azure-pipelines-mirror.yml
trigger: none

schedules:
- cron: "*/10 * * * *"
  displayName: 'Mirror from GitHub'
  branches:
    include:
    - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none

- script: |
    # Use $GITHUB_PAT and $AZURE_PAT (no $()) because they are now env vars.
    git clone --mirror https://$GITHUB_PAT@github.com/SwoopCodes/Computer-Repair-System.git mirror-repo
    
    cd mirror-repo
    
    # Use the environment variable for the Azure PAT here as well.
    git remote add azure https://$AZURE_PAT@dev.azure.com/Computer-Repair-System-PRJ/_git/Computer-Repair-System
    
    git push azure --mirror
  displayName: 'Mirror GitHub to Azure Repos'
  env:
    # Map the secret pipeline variables to environment variables.
    GITHUB_PAT: $(GitHubPAT)
    AZURE_PAT: $(AzureDevOpsPAT)